[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  
# Disable corepack
COREPACK_ENABLE = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200